### ISSUE TITLE
Setup a folder for metadata

### ISSUE THREAD

**Issue by licaon-kter** [podverse/podverse-fdroid#10]
eg. _(summary/description/images/changelog/etc)_ in a [Fastlane](https://gitlab.com/snippets/1895688) or [Triple-T](https://gitlab.com/snippets/1901490) folder structure

...and remove Summary and Description from the .yml

**Comment by mitchdowney** [comment]
Thank you for the info! I tried setting up a Fastlane directory, and created a PR in the fdroiddata repo https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7432
