### ISSUE TITLE
Importing OPML file from Stitcher Does Nothing

### ISSUE THREAD

**Issue by landry314** [podverse/podverse-fdroid#136]
Just nothing happens when I import the OPML file I just exported from the dying Stitcher app.

I don't know... do I need an account logged in? I am able to manually subscribe to podcasts without one.

**Comment by mitchdowney** [comment]
Hi @landry314, thanks for the bug report. I just moved this issue to the podverse-rn repo, which is the "upstream" repo for our F-Droid code. I'll reply there.

https://github.com/podverse/podverse-rn/issues/1841
