### ISSUE TITLE
Usage of the camera package without non-FOSS deps

### ISSUE THREAD

**Issue by licaon-kter** [podverse/podverse-fdroid#14]
https://github.com/react-native-camera/react-native-camera/issues/2845#issuecomment-700143920

Via the Joplin F-Droid RFP

**Comment by mitchdowney** [comment]
Thanks for sharing. There is no need for a camera package at all in the F-Droid version, and I thought I removed all traces of it already..although I see `react-native-camera` is in the missingDimensionStrategy field of the build.gradle file:

```
    defaultConfig {
        applicationId "com.podverse.fdroid"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "2.10.1"
        multiDexEnabled true
        missingDimensionStrategy 'react-native-camera', 'general'
```

I'm not sure if removing `react-native-camera` is what is needed to resolve this issue. Do you know by chance? If not I'll look into more.

**Comment by licaon-kter** [comment]
No idea :)

**Comment by mitchdowney** [comment]
react-native-camera is no longer a part of podverse-fdroid
