### ISSUE TITLE
Red Triangle at Play button

### ISSUE THREAD

**Issue by Perlover** [podverse/podverse-fdroid#150]
F-Droid v4.14.0, phone Fold 5

I cannot play podcasts - I see a red triangle some warning at Play button. What does it mean?

Example:

https://i.nostr.build/Z4aQ.jpg

P.S. After installing I connected with Alby account for Value4Value feature.

**Comment by Perlover** [comment]
V4.14.1 from Google Play - the same problem
I used podcast rss from here: https://learningenglish.voanews.com/rssfeeds

**Comment by mitchdowney** [comment]
@Perlover this link https://learningenglish.voanews.com/rssfeeds points to a web page that has links to RSS feeds, but that link is not an RSS feed itself. Can you provide a link to a specific RSS feed from that page that has the issue for you?

**Comment by Perlover** [comment]
Any rss feed from there page

For example:

https://learningenglish.voanews.com/api/zkm-qemb-o

**Comment by mitchdowney** [comment]
So when I search for `enclosure` tags in that RSS feed, I am only seeing image enclosures, but not audio enclosures. For example:

```
<enclosure url="https://gdb.voanews.com/01000000-c0a8-0242-c0a3-08db896660c8_cx0_cy7_cw0_w800_h450.jpg" length="0" type="image/jpeg"/>
```

It would appear this is not a valid _podcast_ RSS feed. It looks more like a _blog_ RSS feed. Our system is only setup to work with podcast RSS feeds, so we're not going to be able to support blog feeds like this right now.

**Comment by Perlover** [comment]
Thank you! I thought that these are podcast feeds :-/

I will close the ticket now and will try a valid feed.
