### ISSUE TITLE
custom RSS crash

### ISSUE THREAD

**Issue by njakes** [podverse/podverse-fdroid#23]
Using the latest version on Fdroid (3.0.2) it instantly crashes the app as soon as the 'Add Custom RSS' button is pushed.

**Comment by mitchdowney** [comment]
Sorry, what an epic fail 🤦‍♂️  we're going to try to get a new release out this week. I'll make sure the Add Custom RSS button doesn't crash before publishing to F-Droid.

**Comment by mitchdowney** [comment]
This was fixed after 3.0.2
