### ISSUE TITLE
Cannot search Chinese podcasts

### ISSUE THREAD

**Issue by tmsbrg** [podverse/podverse-fdroid#24]
Hey there! First of all, thanks for creating this app. Saw it on F-droid recently and found it's great, now following a bunch of podcasts.

One thing I noticed is that even though there are Chinese language podcasts in the database, I cannot find them by typing Chinese characters. Example (this works both in the app and on https://podverse.fm/search ):
 - There is a podcast called UFM100.3-一天一悟
 - I can find it by searching UFM (the English text part)
 - But if I search for "一天一悟" in the app or web, I don't find anything (actually, it seem to match a whole bunch of random stuff)

I thought I'd report it so you guys know about it.

**Comment by mitchdowney** [comment]
@tmsbrg thanks so much for reporting this. We haven't really tested the app with non-English languages yet. We'll keep this on our radar and try to expand our testing into other languages soon.

**Comment by mitchdowney** [comment]
Since this is a data API issue rather than a podverse-fdroid issue, I created a copy of this issue in podverse-api. Closing this issue here.
