### ISSUE TITLE
Searching always results in an error on a device running CalyxOS

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse-fdroid#27]
> I am on CalyxOS on a Pixel and using the Fdroid app. I visited the website on this phone and it worked just fine. I also deleted and reinstalled the app, but that didn't help. Usually I'm on a VPN or using Orbot, but I removed all of that to troubleshoot and I still got the "Network error you must be connected to the internet to search podcast's.

**Comment by hunterstabler** [comment]
I am also having this issue on CalyxOS on a Pixel 4a. It was working fine when I initially set up my subscriptions via search and RSS. but when I recently tried to add more podcasts, I get the error every time. I am not sure how to add error logs or anything, so I apologize.

**Comment by mitchdowney** [comment]
@hunterstabler thanks for letting us know. This is unfortunately a very mysterious one as we have not been able to reproduce it on our devices :( it is way too common though. We _have_ to track down what is going on here...

We just submitted a new release to F-Droid today (v3.2.0). I don't think any of our changes should resolve this issue...but maybe?

Also, some extra info for debugging: are you logged in to the app, or using it without logging in?

**Comment by mitchdowney** [comment]
We're consolidating the Podverse mobile app issues into the podverse-rn issue, so I just copied this issue over to podverse-rn  https://github.com/podverse/podverse-rn/issues/807
