### ISSUE TITLE
Skipping from bluetooth controls does not work 

### ISSUE THREAD

**Issue by DoloresHA** [podverse/podverse-fdroid#36]
When I am listening to a podcast through my car stereo, the play/pause buttons on my car work, but the skip forward/backward buttons do nothing, despite them working on other player apps.

**Comment by mitchdowney** [comment]
@DoloresHA I'm so sorry for the delay 🤦‍♂️ we have been prioritizing adding screen reader support for the past couple months, and a lot of Chapters improvements, and I've fallen behind on Github issues.

This is a great idea, and I actually just ran into this feature myself for the first time a couple days ago. I was listening to an episode with chapters, and wanted to skip the chapter with the skip track button in my car, but it didn't work.

I _think_ this should be easy to add in our existing setup. I just [pushed this code](https://github.com/podverse/podverse-rn/commit/7ecf3e81ef68f0e577ba6af1e504f28e2aaaa908), and we'll try it in our Beta soon.

Unfortunately though, our F-Droid release process is currently blocked, and it might be a couple weeks before we can fix that :( the bluetooth feature should be in our Apple or Google Play releases sooner though.

**Comment by mitchdowney** [comment]
@DoloresHA the skipping and previous function should now work on car stereos as of Podverse 3.2.4. If you have any issues please let me know.
