### ISSUE TITLE
Support for Private RSS Feeds

### ISSUE THREAD

**Issue by Frikster** [podverse/podverse-fdroid#46]
Does the app support private RSS feeds such as those offered by premium subscribers to certain podcasts? I cannot find this feature on the Podverse Premium feature set nor anywhere in the free tier of the app.

So, I guess not?

Any plans to add this feature? It is supported on most major podcast apps far as I can tell.

**Comment by mitchdowney** [comment]
Hello! Do you mean premium feeds that can be added manually with a URL? If yes, the "Add Custom RSS Feed" button on the More Screen should work for this purpose (for example, for Patreon premium feeds).

Or do you mean premium feeds that are password protected? We actually do offer this in Podverse 3.2.0 for iOS and Android, but we have been unable to release 3.2.0 to F-Droid as we have been blocked with an issue related to the srclibs configuration in our build pipeline.

I have been in communication with F-Droid team members over the past couple weeks, but we have not corresponded for 5 days. Unfortunately this and all future Podverse F-Droid releases are blocked until we can resolve this srclibs issue...

The discussion is scattered, but I left off at this point: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9726#note_674607904

I will reach out to the F-Droid team again tonight to see if we can get help debugging this. We unfortunately are stumped as to how to resolve this issue...

**Comment by Frikster** [comment]
@mitchdowney I am happy to report that after getting in touch with the podcast provider I am in contact with it looks like an issue on their end and it works after getting a new Private RSS feed link from them!

So Podverse does indeed support Private RSS Feeds! I'd recommend advertising this fact. For instance you are not on this list: https://support.supercast.com/article/67-podcast-players-that-support-private-rss-feeds

The Patreon premium feed I am subscribed to will recommend I use some podcast apps (namely Podcast Addict, Pocket Cast or a bunch of iOS ones) but will explicitly tell me that some apps like Spotify, iHeartRadio and stitcher do NOT support private RSS feeds.

It is easy to assume that since Podverse isn't listed as supported anywhere and that private RSS feeds is something some apps don't support that Podverse falls on the unsupported side since nowhere online can I find information that it is supported.

**Comment by mitchdowney** [comment]
Glad it's working for you 😅 and thanks for tip on Supercast! I just sent them an email their website to ask if they would add us to their list.
