### ISSUE TITLE
Support for .mp3/.m4a/PSC chapters

### ISSUE THREAD

**Issue by Inrumpo** [podverse/podverse-fdroid#47]
I know that the Podcasting 2.0 chapters are supposed to be the new fancy ones. However, many podcast do not support those separate JSON file chapters; instead they put the chapters directly in the audio file (.mp3/.m4a) or in the RSS feed ([Podlove Simple Chapters](https://podlove.org/simple-chapters/) [PSC]).

Therefore I'd really like Podverse to support those kind of chapters too. That's the only missing feature stopping me from abandoning Pocket Casts.
I've heard that .m4a chapters can be tricky on Android; ~~I don't know how AntennaPod is doing it~~. On the other hand implementing Podlove Simple Chapters should be rather easy. Those could even be made visible in the web player.

I promise I won't tell Dave and Adam. 😉

---

AntennaPod offers a folder with audio files containing chapter marks to test the chapter implementation of own applications:
https://github.com/AntennaPod/AntennaPod/tree/develop/parser/media/src/test/resources

**Comment by mitchdowney** [comment]
Haha. We have nothing against audio-embedded chapters, and we think they actually have a very important role to play in the future for addressing issues with dynamic content insertion. Embedded chapters just haven't made it to the top of our work queue yet.

It should be fairly simple for us to plug the chapter data into the existing UI logic though. There are just two things that are kind of blocking me...

1) How to extract metadata from the mp3 (and other?) files?

2) How to parse out the psc:chapter tags from the metadata?

If someone can help with writing that in JavaScript, it should only take a day or two for us to add it to the app. Thanks for the idea! 🙂

**Comment by heikopanjas** [comment]
Podlove Simple Chapter are covered in detail at https://podlove.org/simple-chapters/. This also includes an example. If you are using an XML parser that knows how to do XPath, a quick `select` should do the trick.

**Comment by Inrumpo** [comment]
You can read Podlove Simple Chapters directly from the feed. I assume Podverse is reading the RSS feed anyway. 

It looks like this:
![Screenshot 2021-09-24 212321](https://user-images.githubusercontent.com/11300164/134729320-04b72cfb-5077-487d-b50a-d3f1e1d9312f.png)

This example is from the RSS feed `https://gametalk.fm/feed/m4a`.

**Comment by Inrumpo** [comment]
@mitchdowney Have you been able to make some progress? Is there anything specific you need help with?

**Comment by mitchdowney** [comment]
Sorry @lnrumpo, this fell off my plate. There's so much to work on it's hard for me to say when I can get to this. I will at least move this ticket over to podverse-rn though since we consolidate all our mobile app work over there (since podverse-fdroid is just a downstream fork of podverse-rn).
