### ISSUE TITLE
Display <itunes:subtitle> in episode overview, if available

### ISSUE THREAD

**Issue by Inrumpo** [podverse/podverse-fdroid#50]
## Status quo
As of now (F-Droid Version 3.1.11) Podverse is displaying the `<description>` tag in the episode overview:

![Podverse iTunes Subtitle](https://user-images.githubusercontent.com/11300164/134665904-b1352b6c-866d-44f3-b462-bd6e11be287c.jpg)

## Issue
Since space is very limited, those descriptions are getting truncated heavily. The result is not very useful. The user hardly gets any information out of this.

## Solution
Luckily there is another (old) RSS feed tag for this usecase: The **subtitle**. Even though that tag doesn't get much love lately for reasons unknown, it would fit perfectly. iTunes arguably showing the subtitle only in rare cases doesn't make this any less useful. A subtitle is what comes after/under a title and provides (hinting) information in a short and compact (and plaintext) way. Perfect! Some more [information on this tag here](https://www.feedforall.com/itune-tutorial-tags.htm#subtitle).

## Proposal
Display the content of the `<itunes:subtitle>` RSS feed tag in a podcast's episode overview, if available. If not available, fall back to truncated `<description>` content.

**Comment by mitchdowney** [comment]
@Inrumpo this is a great idea. I didn't realize the `<itunes:subtitle>` tag was here for that purpose.

We'll need to update our server-side RSS parser (in podverse-api) extract the value and save it to our Episodes database table, and the client-side RSS parser (for custom feeds, used in podverse-rn) to extract the value and save it locally to the app.

Should be an hour or two of work. I'll try to get this in a release sometime in October.

**Comment by mitchdowney** [comment]
Sorry @lnrumpo, alas this fell off my plate. There's so much to work on it's hard for me to say when I can get to this. I will at least move this ticket over to podverse-rn though since we consolidate all our mobile app work over there (since podverse-fdroid is just a downstream fork of podverse-rn).

**Comment by mitchdowney** [comment]
@Inrumpo I finally got around to replacing descriptions with subtitles across the apps. Right now the subtitle field hasn't been parsed for all podcasts, so the change may not be noticeable site-wide for a few weeks. If you know of any RSS feeds that use different value for the subtitle field than the description please lmk and we can test it.

Related PRs/commits:

https://github.com/podverse/podverse-api/pull/436/files

https://github.com/podverse/podverse-rn/commit/1f82567b184288e822266176f681425415588f4a

https://github.com/podverse/podverse-web/pull/682/files

**Comment by mitchdowney** [comment]
Whoops I wasn't supposed to comment in the F-Droid repo 🤦‍♂️  lol
