### ISSUE TITLE
Episodes are streamed even when downloaded locally

### ISSUE THREAD

**Issue by bobdanek** [podverse/podverse-fdroid#51]
Podverse appears to be streaming podcast episodes, even if I have already downloaded them locally.

Symptoms:
* jump ahead / jump back takes a long time, which doesn't make sense if the file is locally available
* cannot listen to downloaded episodes when in offline mode or when phone is in airplane mode

Phone: Pixel 5
OS: GrapheneOS 2021092612
Podverse version: 3.1.11 for F-Droid

**Comment by mitchdowney** [comment]
Oh no 😨 that's a serious bug. I imagine it should be an easy fix in our logic somewhere because it was working at some point...I'll take a look tonight. Thanks a lot for reporting this 🙏

**Comment by bobdanek** [comment]
Thanks for the super quick response! And for all your hard work on this!

**Comment by mitchdowney** [comment]
@bobdanek good to hear 😅 let us know if you have any more bug reports / feature requests.

**Comment by msdosfx** [comment]
bobdanek, where did you change that setting? I am having this issue. Do you have to change it to Offline Mode in order for it to play from downloaded?

**Comment by mitchdowney** [comment]
@msdosfx what version of the app do you have? You can go to More > About > scroll to bottom to copy the version info.

**Comment by msdosfx** [comment]
I have version 4.3.5. My

**Comment by mitchdowney** [comment]
@msdosfx thanks for your kind feedback, and sorry for the late reply.

v4.3.5 is a _very_ old version, so hopefully that is the issue?

In any case, there was a critical bug that we fixed recently with "Add by RSS" downloaded episodes in 4.5.11. We also disabled some of our "automatic offline mode" handling as it was causing more problems than it solved.

I'm not sure if either of those changes will fix the issues you are running into though...if you have downloaded an episode, then it should continue to play for you whether you lose/switch internet access or not. If you are still seeing this issue in 4.5.11+ please let me know and we'll prioritize it.

**Comment by trev-dev** [comment]
I'm currently having this problem.  Version 4.6.6.  I'm going to wipe my data and re-try.  The app used 2.5Gb in 2 dog walks xD

**Comment by mitchdowney** [comment]
@trev-dev oof 😳  are you using iOS, Google Play, or F-Droid? And the episodes you were playing were downloaded?

**Comment by mitchdowney** [comment]
@trev-dev oh, I see this is the F-Droid repo so presumably you're using F-Droid. We don't use the issue tracker in this repo. Instead we use the Issue tracker in https://github.com/podverse/podverse-rn since they're both the same app, except the F-Droid version has some things removed like tracking and libraries that don't have an F-Droid compatible license.

I just created this ticket. Can you continue this conversation over there? Also, what Android OS are you using? https://github.com/podverse/podverse-rn/issues/1283
